### ISSUE TITLE
Unable to compile and install for Elixir 1.11 due to :inets not being listed as a dependency

### ISSUE THREAD

**Issue by chazwatkins** [TheFirstAvenger/ironman#36]
## Problem
When trying to do `mix archive.install hex ironman` using Elixir 1.11 a warning/error causes compilation failure.

![image](https://user-images.githubusercontent.com/9411090/98192676-12fd5800-1ee1-11eb-97ea-42b8715cfb5f.png)

**Comment by TheFirstAvenger** [comment]
Fixed in v0.4.6. `mix archive.install hex ironman` to update
https://hex.pm/packages/ironman/0.4.6
